#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroCode.HtmlHelpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Helpers/MyHelper.cshtml")]
    public partial class MyHelper : System.Web.Mvc.WebViewPage<dynamic>
    {

#line 1 "..\..\Views\Helpers\MyHelper.cshtml"
public static System.Web.WebPages.HelperResult Funcg(string name) 
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 2 "..\..\Views\Helpers\MyHelper.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div>\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 4 "..\..\Views\Helpers\MyHelper.cshtml"
WriteTo(__razor_helper_writer, name);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n    </div>\r\n");


#line 6 "..\..\Views\Helpers\MyHelper.cshtml"


#line default
#line hidden
});

#line 6 "..\..\Views\Helpers\MyHelper.cshtml"
}
#line default
#line hidden

        public MyHelper()
        {
        }
        public override void Execute()
        {
        }
    }
}
#pragma warning restore 1591
