//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroCode.Repository.Data
{
    
    
    using System;
    using System.Collections.Generic;
    
    public partial class User:IEntity<string>
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gander { get; set; }
        public Nullable<int> Position { get; set; }
    
    }
}
